### ISSUE TITLE
Update pgrx to 0.12.1

### ISSUE THREAD

**Issue by olirice** [supabase/wrappers#336] opened 2024-08-26 21:06 UTC
Update pgrx to 0.12.1 in support of downstream consumers in need of latest pgrx features

ref:
https://github.com/paradedb/paradedb/pull/1550

**Comment by burmecia** [comment] 2024-08-27 06:35
there is [an upstream issue](https://github.com/pgcentralfoundation/pgrx/issues/1822) in pgrx, wait for it to be resolved.

**Comment by workingjubilee** [comment] 2024-08-27 19:27
@burmecia That won't be resolved unless it becomes reproducible. The issue is probably that you have too many clangs installed and you need to uninstall all except one.

**Comment by burmecia** [comment] 2024-08-28 13:43
thanks @workingjubilee , I've reproduced that issue and commented [here](https://github.com/pgcentralfoundation/pgrx/issues/1822#issuecomment-2315355635)

**Comment by Vonng** [comment] 2024-10-14 03:48
Is there any plan to bump pgrx version to 0.12.5?

**Comment by burmecia** [comment] 2024-10-14 04:48
The pgrx 0.12.5 doesn't support Ubuntu 20 yet, but there is [a fix for that](https://github.com/pgcentralfoundation/pgrx/pull/1885) already be merged. We've a [draft PR](https://github.com/supabase/wrappers/pull/351) ready for that and now just wait for pgrx's next new version to be released.

**Closed** 2024-10-15 06:03 UTC
Labels: bug
