### ISSUE TITLE
wrappers_fdw_stats in read-only query

### ISSUE THREAD

**Issue by StanGirard** [supabase/wrappers#195] opened 2023-11-21 00:00 UTC
https://github.com/supabase/wrappers/pull/188 issue not fixed when querying stripe on the hosted version.

<img width="1047" alt="image" src="https://github.com/supabase/wrappers/assets/19614572/cc99fa67-7d3c-4a93-bece-aed92efed365">
<img width="369" alt="image" src="https://github.com/supabase/wrappers/assets/19614572/a75168f9-fa59-4c83-97ee-afc82e885beb">
<img width="601" alt="image" src="https://github.com/supabase/wrappers/assets/19614572/094e4416-09b6-4ea1-800e-ecec7916fdf0">
<img width="634" alt="image" src="https://github.com/supabase/wrappers/assets/19614572/e6fed370-896e-4ce1-b802-e7da798552c0">

**Comment by imor** [comment] 2023-11-21 05:46
@StanGirard the issue is fixed in `wrappers` version `0.1.19` but we haven't yet rolled out an image that includes this version on the platform. If it's urgent, you can raise a support ticket and we will update your project to the latest `wrappers` version.

**Closed** 2024-02-15 07:54 UTC
Labels: bug
